network: support for uPnP and PMP nat traversal
codex-storage/nim-codex pull request #1050
Opened 2024-12-18 09:47 UTC by munna0908

This PR introduces support for new NAT traversal techniques.  Issue: #905 

## Changes Include
- Modified the `nat` CLI flag: Allowing users to select from various options for determining the public address. The available options are:
  * any: Automatically selects any available method.
  * none: Disables NAT detection.
  * upnp: Uses UPnP (Universal Plug and Play) for NAT traversal.
  * pmp: Uses PMP (Port Mapping Protocol) for NAT traversal.
  * extip:<IP>: Specifies a custom external IP address.
- Removed `disc-ip` flag: The IP address will now be automatically parsed from the provided listener address

2024-12-20 18:26 UTC, gmega reviewed
Made some minor suggestions but otherwise looks good to me. As soon as the CI issue is fixed, I think we're good to go.

2024-12-20 18:26 UTC, gmega commented on codex/conf.nim
> +export units, net, codextypes, logutils,completeCmdArg,parseCmdArg,NatConfig
```suggestion
export units, net, codextypes, logutils, completeCmdArg, parseCmdArg, NatConfig
```

2024-12-20 18:26 UTC, gmega commented on tests/codex/testnat.nim
> +  test "natedAddress with local addresses":
```suggestion
  test "nattedAddress with local addresses":
```

2025-01-07 10:43 UTC, munna0908 commented on tests/codex/testnat.nim
> +  test "natedAddress with local addresses":
Fixed. [Commit](https://github.com/codex-storage/nim-codex/pull/1050/commits/b387b6aff4251772176098f0fea007caa0630201)

2025-01-07 10:43 UTC, munna0908 commented on codex/utils/addrutils.nim
> +    return MultiAddress.init("/ip6/" & $ip & "/udp/" & $port).expect("valid multiaddr")
Fixed. [Commit](https://github.com/codex-storage/nim-codex/pull/1050/commits/b387b6aff4251772176098f0fea007caa0630201)

2025-01-07 10:43 UTC, munna0908 commented on codex/codex.nim
> +  let (announceAddrs,discoveryAddrs)= natedAddress(
Fixed. [Commit](https://github.com/codex-storage/nim-codex/pull/1050/commits/b387b6aff4251772176098f0fea007caa0630201)

2025-01-07 11:59 UTC, gmega commented on build.nims
> +      renameFile(newVersionFile, oldVersionFile)
```suggestion
  finally:
    # This is a quick workaround to avoid VERSION file conflict on macOS
    # More details here: https://github.com/codex-storage/nim-codex/issues/1059
    if defined(macosx):
      renameFile(newVersionFile, oldVersionFile)
```

2025-01-07 12:44 UTC, gmega requested changes
We're close now.

2025-01-07 12:44 UTC, gmega commented on build.nims
> +      renameFile(newVersionFile, oldVersionFile)
Careful @munna0908 as you're not using consistent spacing to indent the levels, and this can lead to very difficult-to-read code. Sadly the Nim compiler will apparently let you get away with it. We use 2 spaces per level.

2025-01-07 12:44 UTC, gmega commented on tests/codex/testnat.nim
> +    check(libp2pAddrs == expectedlibp2pAddrs)
```suggestion
    check(libp2pAddrs == expectedlibp2pAddrs)

```

2025-01-07 12:44 UTC, gmega commented on codex/utils/addrutils.nim
> +    result = (ip: none(ValidIpAddress), port: none(Port))
```suggestion
    result = (ip: none(ValidIpAddress), port: none(Port))

```

2025-01-07 14:02 UTC, gmega commented
@veaceslavdoina @benbierens Rahul is making some changes to the way NAT parameters work, we should make sure that all users of those (e.g. testnet deployers, disttests deployers) are not gonna fall apart, would be good to have your eyes here.

2025-01-07 14:04 UTC, munna0908 commented on codex/utils/addrutils.nim
> +    result = (ip: none(ValidIpAddress), port: none(Port))
[Fixed](https://github.com/codex-storage/nim-codex/pull/1050/commits/2bae744c5c9a5be4dcf5300196cdb756b916185a)

2025-01-07 14:04 UTC, munna0908 commented on tests/codex/testnat.nim
> +    check(libp2pAddrs == expectedlibp2pAddrs)
[Fixed](https://github.com/codex-storage/nim-codex/pull/1050/commits/2bae744c5c9a5be4dcf5300196cdb756b916185a)

2025-01-07 14:04 UTC, munna0908 commented on build.nims
> +      renameFile(newVersionFile, oldVersionFile)
Gotcha!

2025-01-07 21:23 UTC, dryajov commented on codex/utils/addrutils.nim
> +    result = (ip: none(ValidIpAddress), port: none(Port))
Minor nitpick, we usually add a new line at the end of the file, most IDEs should have a setting to insert one by default.

2025-01-07 23:39 UTC, gmega approved these changes
Looks good as far as I'm concerned.

2025-01-08 09:23 UTC, marcinczenko commented on build.nims
> +      renameFile(newVersionFile, oldVersionFile)
nothing really big on my side, but just wondering - is it so important to rename that "version" file? If we just delete it, we could simplify have a one single compact change, like this:

```nim
### Helper functions
proc buildBinary(name: string, srcDir = "./", params = "", lang = "c") =
  when defined(macosx):
    # temporary fix for the conflicting "VERSION" file in
    # https://github.com/miniupnp/libnatpmp that causes a conflict
    # with "#include <VERSION>" from the std library:
    proc deleteVersionFile() =
      let versionFilePath = "vendor/nim-nat-traversal/vendor/libnatpmp-upstream/VERSION"
      echo "deleting " & versionFilePath
      if fileExists(versionFilePath):
        rmFile(versionFilePath)
    deleteVersionFile()
``` 

also notice using `when defined(macosx)` instead of `if defined(macosx)`.

2025-01-08 10:26 UTC, gmega commented on build.nims
> +      renameFile(newVersionFile, oldVersionFile)
You can debate this with @dryajov :-)

2025-01-09 10:48 UTC, munna0908 commented on codex/utils/addrutils.nim
> +    result = (ip: ip, port: port)
Gotcha. [commit](https://github.com/codex-storage/nim-codex/pull/1050/commits/0934e59801b2b058ccc718f249b2759132962ebb)

2025-01-09 10:48 UTC, munna0908 commented on codex/nat.nim
> +func parseCmdArg*(T: type NatConfig, p: string): T {.raises: [ValueError].} =
[commit](https://github.com/codex-storage/nim-codex/pull/1050/commits/0934e59801b2b058ccc718f249b2759132962ebb)

2025-01-09 14:28 UTC, gmega commented
If you're done addressing the comments, @munna0908, feel free to merge.

2025-01-09 19:20 UTC, merged