Proof/data sampler
codex-storage/nim-codex pull request #639
Opened 2023-11-27 12:24 UTC by benbierens

2023-11-27 12:53 UTC, benbierens commented
Heads-up: There's a small bug in the assembly in Constantine that needs to get fixed before this thing will work. The PR for that is open here: https://github.com/mratsim/constantine/pull/306

2023-11-28 09:56 UTC, benbierens commented
The constantine update was pulled in and the sampler output has been brough up-to-date with the circuit reference code.
Discussed with Dmitriy and we're holding off merging this one until the merkle tree update has been finished and interested.

2024-01-07 10:09 UTC, benbierens commented
Data sampler should now be aligned with slot builder.

2024-01-10 08:09 UTC, benbierens commented on codex/proof/datasampler.nim
> +  DataSampler* = ref object of RootObj
The expected lifecycle for DataSampler objects is to stay in-memory for as long as a slot is being hosted. Combined with the constructor/start proc split, this thing should be a ref type.

2024-01-10 15:23 UTC, dryajov commented on codex/slots/converters.nim
> +  success verifiableProof
new line at end of file.

2024-01-10 15:25 UTC, dryajov commented on codex/proof/slotblocks.nim
> +import std/sequtils
This isn't needed, just use `slotsBuilder.buildSlot(idx)` and everything will be taken care of.

2024-01-10 15:27 UTC, dryajov commented on codex/proof/datasampler.nim
> +  without starter =? (await startDataSampler(self.blockStore, manifest, self.slot)), e:
you can initialize the builder with a verifiable manifest and it will unpack and set the slots and root hashes.

2024-01-10 15:36 UTC, dryajov requested changes
Good progress, but lets wait for #668 to land, as there are additional changes that should simplify this considerably.

2024-01-11 10:53 UTC, benbierens commented
There's a lot of overlap between what's happening in the slot builder and parts of the data sampler code. But they mismatch in subtle but important ways. For example: slot builder digests block-cells to get their block-roots. Data sampler does the same thing but needs the tree to get proof instead. Slot builder builds and stores the tree for a slot. Data sampler does the same, but only if the tree can't be loaded from disk. Slot builder retrieves blocks if needed. Data sampler does the same, but batched and with an onBatch callback to support so marketplace shenanigans. We can unify these things make it work, but it'll take some changes.

2024-01-18 17:40 UTC, closed without merging